### ISSUE TITLE
BANKCODE data issue

### ISSUE THREAD

**Issue by ujjwala2318** [razorpay/ifsc#113]
https://ifsc.razorpay.com/YESB0ADB001 - this is giving BANKCODE as AVDX.
https://ifsc.razorpay.com/YESB0ADB002 - this is giving BANKCODE as YESB.
But these are two branches of the same bank.
Please clarify, thanks.

**Comment by captn3m0** [comment]
Please see the NPCI Website for sublet branches: https://www.npci.org.in/national-automated-clearing-live-members-1

The FAQ explains this a bit more: https://github.com/razorpay/ifsc/wiki/FAQ

**Comment by ujjwala2318** [comment]
Thanks but in this case the sub-bank has multiple branches.
For the main branch your db is storing BANKCODE and BANK (name) of the sub-bank. But for the other branches your db is storing BANKCODE and BANK (name) of the large bank. That seems to be an anomaly.

https://ifsc.razorpay.com/YESB0ADB002 is a branch of Amravati District Central Coop Bank. Is it correct to say that BANK (name) is Yes Bank? Especially given that https://ifsc.razorpay.com/YESB0ADB001 is showing BANK (name) is Amravati District Central Co-operative Bank.

**Comment by captn3m0** [comment]
Thanks for the explanation, I get what you mean now.

There seem to be a lot of branches+banks where Yes Bank is doing this: http://rbidocs.rbi.org.in/rdocs/Content/DOCs/IFCB2009_100.xlsx

Ideally, we'd want the API to send back `AVDX` for all of these scenarios. However, the only dataset with the sublet mappings currently is the NPCI page I linked above.

Since Yes Bank has the series very clearly defined (`YESB0ZSBL**` = "ZILA SAHKARI BANK LUCKNOW ", `YESB0YUCB**`=`THE YAVATMAL URBAN CO.OP. BANK LTD. YAVATMAL`) etc - we could maybe list down all such prefixes and use them accordingly.

However, till we have a clear dataset that defines all sublet mappings, this will be on a best-effort basis, and we cannot guarantee correctness or coverage.

Will take it up in the next release.

**Comment by captn3m0** [comment]
Closing this for #114

**Comment by ujjwala2318** [comment]
Hi any luck with fixing this issue?

https://ifsc.razorpay.com/MAHG0005401 - this is giving BANKCODE as MAHB
https://ifsc.razorpay.com/MAHB0RRBMGB - this is giving BANKCODE as MGBX

But these are two branches of the same bank: Maharashtra Gramin Bank.
MGBX is the correct BANKCODE for this bank.
MAHB is the BANKCODE for the larger bank Bank of Maharashtra.
