### ISSUE TITLE
Errors against `NMGB` and `OIBA0000001`

### ISSUE THREAD

**Issue by mempersiahsueykan** [razorpay/ifsc#26]
IFSC code with NMGB, the bank name is null in csv and also json releases

edit:
ifsc api shows correct bank name,

for OIBA0000001 branch name blank, 
rbi shows OMAN INTERNATIONAL BANK SAOG's branch name as Mumbai
ifsc api for this code return bank name HSBC Bank Oman S.A.O.G

**Comment by captn3m0** [comment]
NMGB -> Looks like a bug. Will take a look. It is correct on the API, because it overwrites the bank names using its own list. So it reads the null and replaces it with the correct bank name.

`OIBA0000001` -> Looks broken. Will have to check against the spreadsheets to figure out.

Thanks for reporting.

**Comment by captn3m0** [comment]
@mempersiahsueykan 

I've filed changes for the NMGB issue https://github.com/razorpay/ifsc/pull/27. The changes should help a few other banks as well (with regards to contact number formatting), so thanks a lot for bringing this to our notice.

However, regarding `OIBA0000001`, Oman International Bank merged with HSBC a while back to create `HSBC Bank Oman S.A.O.G`. You can see http://www.about.hsbc.co.om/hsbc-in-oman regarding the same. RBI is still publishing them as 2 separate banks, however. 

### [163.xls - HSBC Bank Oman Saog](http://rbidocs.rbi.org.in/rdocs/Content/DOCs/IFCB2009_163.xls):

| BANK                | IFSC        | MICR CODE | BRANCH  | ADDRESS                                            | CONTACT  | CITY   | DISTRICT | STATE       |   |
|---------------------|-------------|-----------|---------|----------------------------------------------------|----------|--------|----------|-------------|---|
| HSBC BANK OMAN SAOG | OIBA0000001 | 400210002    | RTGS-HO | 201,RAHEJA CENTRE, FPJ MARG, NARIMAN POINT, MUMBAI | 22856987 | MUMBAI | MUMBAI   | MAHARASHTRA |   |

### [54.xls - Oman International Bank](http://rbidocs.rbi.org.in/rdocs/Content/DOCs/IFCB2009_54.xls) 

| BANK                         | IFSC CODE   | MICR CODE | BRANCH NAME | ADDRESS                                                                     | CONTACT  | CITY   | DISTRICT        | STATE |   |   |
|------------------------------|-------------|-----------|-------------|-----------------------------------------------------------------------------|----------|--------|-----------------|-------|---|---|
| OMAN INTERNATIONAL BANK SAOG | OIBA0000001 | 400210002  | MUMBAI      | 201, RAHEJA CENTRE, FREE PRESS, JOURNAL MARG, NARIMAN POINT, MUMBAI 400 021 | 66324848 | MUMBAI | GREATER MUMBAI  |       |   |   |

This is what our API currently returns:

```json
{
  "BANK": "HSBC Bank Oman S.A.O.G",
  "IFSC": "OIBA0000001",
  "BRANCH": null,
  "ADDRESS": "201, RAHEJA CENTRE, FREE PRESS, JOURNAL MARG, NARIMAN POINT, MUMBAI 400 021",
  "CONTACT": null,
  "CITY": 66324848,
  "DISTRICT": "MUMBAI",
  "STATE": "GREATER MUMBAI "
}
```

We are picking up the data from the first time we see it (54.xlsx). We are not picking up the branch name because of the wrongly name header in that file: `BRANCH NAME` instead of `BRANCH`. While we'll be fixing the branch name, RBI publishing 2 different branch details for the same IFSC is the real issue here.

**Comment by captn3m0** [comment]
Here is the diff across all branches for this change: https://github.com/razorpay/ifsc-api/commit/dd16685e4e0321adea4e00f5ea0753d964376ce4

Will close this issue once a new release is out. Since this does not change the validator or offline clients in any way, this will be a API/dataset only release.

**Comment by captn3m0** [comment]
The changes have been deployed to the API.

**Comment by captn3m0** [comment]
These changes are part of the new release (1.0.4)
