### ISSUE TITLE
Missing IFSC of State Bank Of Hyderabad

### ISSUE THREAD

**Issue by transhapHigsn** [razorpay/ifsc#93]
On Searching for IFSC "SBHY0020039", API returns 404 response. But this is a legit State Bank Of Hyderabad branch.

Search URL used is 'https://ifsc.razorpay.com/SBHY0020039'  

Looked for the bank in bank name JSON, it was missing from there. So, I am guessing this bank is not supported. Is there any possibility that this bank will be supported in future?

**Comment by captn3m0** [comment]
This is no longer a valid IFSC Code since the SBI Merger. The [RBI Website](https://www.rbi.org.in/Scripts/bs_viewcontent.aspx?Id=2009) no longer lists it.

This is changed to `SBIN0020039` as per the [official SBI FAQ](https://bank.sbi/portal/web/services/merger-of-associate-banks). If you'd like a list of all such codes affected by the merger, we have one at https://github.com/razorpay/ifsc-api/blob/080e319f6b70f8ef04d6267687574e33b3fc6bee/data/redirects.yml

![image](https://user-images.githubusercontent.com/584253/49018568-c156d980-f1b1-11e8-8d57-0b055df5d0d9.png)

We have no plans to support SBHY in the future.

**Comment by transhapHigsn** [comment]
Thanks for the help.
